# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logins',
            old_name='userid',
            new_name='title',
        ),
    ]
