# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20160821_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupid1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactName', models.CharField(max_length=20)),
                ('MobileNo', models.IntegerField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='logins',
        ),
    ]
