# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20160905_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupid1',
            name='ContactName',
            field=models.CharField(max_length=15),
        ),
    ]
