# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20160905_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='groupid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
