# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20160905_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='contactname',
            new_name='contact_name',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='userid',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='mobilenumber',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='usergroup',
            old_name='groupid',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='usergroup',
            old_name='userid',
            new_name='group_name',
        ),
    ]
